---

fail_fast: false
minimum_pre_commit_version: "3.7.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 36fd65054fc8864b4037d0918904f9331512feb5  # frozen: 1.7.10
    hooks:
      - id: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        additional_dependencies: [ "bandit[toml]" ]
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 8983acb92ee4b01924893632cf90af926fa608f0  # frozen: v0.7.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 1b2427a2b785cc4aac97c19bb4b9a0de063f9547  # frozen: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/markdownlint/markdownlint
    # Ruff version.
    rev: 5a6cc38e9dd10830df11fa5f6a5f44cfe83df389  # frozen: v0.12.0
    hooks:
      - id: markdownlint
