---

fail_fast: false
minimum_pre_commit_version: "3.5.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 4c5b3c81e4356001b472849b05af902064d68515  # frozen: 1.7.7
    hooks:
      - id: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        additional_dependencies: [ "bandit[toml]" ]
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 0431f238e57190b696d22a57a87eb3d0b22c0036  # frozen: v0.3.1
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 6fdf8a4af28071ed1d079c01122b34c5d587207a  # frozen: 24.2.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/markdownlint/markdownlint
    # Ruff version.
    rev: 5a6cc38e9dd10830df11fa5f6a5f44cfe83df389  # frozen: v0.12.0
    hooks:
      - id: markdownlint
