name: 'Run Pre-commit Hooks'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.11'
      - name: Install MDL
        run: echo $'source \'https://rubygems.org\'\ngem \'mdl\', \'~> 0.12.0\'' > Gemfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Pre-commit dependencies
        run: poetry poe install
      - uses: pre-commit/action@v3.0.0
