name: 'Run Pre-commit Hooks'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.11'
      - name: Install MDL
        run: echo $'source \'https://rubygems.org\'\ngem \'mdl\', \'~> 0.12.0\'' > Gemfile
      - uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854  # v1.190.0
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Pre-commit dependencies
        run: poetry run poe install
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
