name: 'Run Pre-commit Hooks'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.13'
      - name: Install MDL
        run: echo $'source \'https://rubygems.org\'\ngem \'mdl\', \'~> 0.13.0\'' > Gemfile
      - uses: ruby/setup-ruby@217c988b8c2bf2bacb2d5c78a7e7b18f8c34daed # v1.200.0
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Pre-commit dependencies
        run: poetry run poe install
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
