name: 'Validation'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-style:
    name: Linting and Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.12'

      - name: Run Styling Enforcement
        shell: bash
        run: poetry run poe check

      - name: Run Style Linting Enforcement
        shell: bash
        run: poetry run poe lint

  unit-tests:
    name: Run Unit Tests
    strategy:
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '${{ matrix.version }}'

      - name: Run Tests
        shell: bash
        run: poetry run poe test

      - name: Codecov
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab  # v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  security:
    name: Run Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.12'

      - name: Run Security Checks
        shell: bash
        run: poetry run poe security
