name: 'Validation'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-style:
    name: Linting and Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.13'

      - name: Run Styling Enforcement
        shell: bash
        run: poetry run poe check

      - name: Run Style Linting Enforcement
        shell: bash
        run: poetry run poe lint

  unit-tests:
    name: Run Unit Tests
    strategy:
      matrix:
        version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '${{ matrix.version }}'

      - name: Run Tests
        shell: bash
        run: poetry run poe test

      - name: Codecov
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a  # v5.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  security:
    name: Run Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Setup Dependencies
        uses: './.github/actions/deps'
        with:
          python-version: '3.13'

      - name: Run Security Checks
        shell: bash
        run: poetry run poe security
